spring.application.name=arthur-nicolas
spring.datasource.url=jdbc:postgresql://localhost:5432/knex_db

spring.datasource.username=postgres

spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update